python batch_cellprofiler.py 6_FluorescentImagery/Input 6_FluorescentImagery/Result_1_Smoothed 6_FluorescentImagery/FluorescentImagery_1_Smoothed.cppipe 2<&1
python batch_cellprofiler.py 6_FluorescentImagery/Input 6_FluorescentImagery/Result_2_BigShapeFilter 6_FluorescentImagery/FluorescentImagery_2_BigShapeFilter.cppipe 2<&1
