# processing Cytation image data from CellProfiler
# Theresa Swayne for SHaron Fleischer, Gordana Vunjak-Novakovic, 2022

# Input: One or more csvs generated by a CellProfiler pipeline with suitable columns, chosen by user
# Important -- the CSVs must be in a folder by themselves, no other CSV files
# Output:  Table and plots of normalized integrated intensity, mean intensity, grouped by well

require(tidyverse)
require(ggplot2)
require(tcltk)

input_dir <- tk_choose.dir(default = "", caption = "Select directory of CellProfiler spreadsheets")

#inputFile <- tk_choose.files(caption = "Select Cellprofiler spreadsheet")
#df <- read.csv(inputFile)
#inputName <- basename(inputFile) # name of the file without higher levels

output_dir <- tk_choose.dir(default = "", caption = "Select output directory")


# Get a list of CSV files in the input folder
files <- dir(input_dir, pattern = "*.csv") 

# Read the data -- parsing errors may occur but data should be read ok.
mergedDataWithNames <- tibble(filename = files) %>% # column 1 = file names
  mutate(file_contents =
           map(filename,          # column 2 = all the data in the file
               ~ read_csv(file.path(input_dir, .))))

# Make the list into a flat file -- each row contains its source filename
df <- unnest(mergedDataWithNames, cols=c(file_contents)) # added in response to 'cols is now required' error



# include only images with a reasonable number of cells
#df_filt <- df %>% filter(Count_Nuclei != 0)
df_filt <- df %>% filter(Count_Nuclei >= 25)

# Normalize the integrated intensity values
df_filt$NormTotalIntensity <- df_filt$Intensity_TotalIntensity_CY5/df_filt$Count_Nuclei

# group the table and summarize in a new table
by_well <- df_filt %>% 
  group_by(Metadata_Well) %>% 
  summarize(mean = mean(Intensity_MeanIntensity_CY5), sdMean = sd(Intensity_MeanIntensity_CY5), norm_intensity = mean(NormTotalIntensity), sdNorm = sd(NormTotalIntensity), mean_num_nuclei = mean(Count_Nuclei))

# remove extraneous columns
df_selected <- df_filt %>% select(FileName_CY5, Count_Nuclei, Intensity_MeanIntensity_CY5, Intensity_TotalIntensity_CY5, NormTotalIntensity, Metadata_Well)

# prepare to plot 2 columns at a time
by_well_AB <- filter(by_well, grepl("A|B", `Metadata_Well`))
by_well_CD <- filter(by_well, grepl("C|D", `Metadata_Well`))
by_well_EF <- filter(by_well, grepl("E|F", `Metadata_Well`))
by_well_GH <- filter(by_well, grepl("G|H", `Metadata_Well`))

df_filt_AB <- filter(df_filt, grepl("A|B", `Metadata_Well`))
df_filt_CD <- filter(df_filt, grepl("C|D", `Metadata_Well`))
df_filt_EF <- filter(df_filt, grepl("E|F", `Metadata_Well`))
df_filt_GH <- filter(df_filt, grepl("G|H", `Metadata_Well`))

# ggplot bar plot of means

# massive plot of all data
p <- ggplot(data=by_well, aes(x=Metadata_Well, y=norm_intensity)) + 
  geom_bar(stat="identity")
ggsave(filename = "all_basic_bar.pdf", width = 16, height = 2, units = "in", path = output_dir)

# plot of 2 columns at a time
pAB <- ggplot(data=by_well_AB, aes(x=Metadata_Well, y=norm_intensity)) + 
  geom_bar(stat="identity")
ggsave(filename = "AB_basic_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)

pCD <- ggplot(data=by_well_CD, aes(x=Metadata_Well, y=norm_intensity)) + 
  geom_bar(stat="identity")
ggsave(filename = "CD_basic_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)

pEF <- ggplot(data=by_well_EF, aes(x=Metadata_Well, y=norm_intensity)) + 
  geom_bar(stat="identity")
ggsave(filename = "EF_basic_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)

pGH <- ggplot(data=by_well_GH, aes(x=Metadata_Well, y=norm_intensity)) + 
  geom_bar(stat="identity")
ggsave(filename = "GH_basic_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)


# ggplot notched box plot of all data
p2 <- ggplot(df_filt, aes(x=Metadata_Well, y=NormTotalIntensity)) + 
  geom_boxplot(notch=FALSE, outlier.colour="red", outlier.shape=8,
               outlier.size=4, position = "dodge") +
  stat_summary(fun=mean, geom="point", shape=23, size=4)

ggsave(filename = "all_notched_bar.pdf", width = 16, height = 2, units = "in", path = output_dir)

# plot 2 columns at a time
p2AB <- ggplot(df_filt_AB, aes(x=Metadata_Well, y=NormTotalIntensity)) + 
  geom_boxplot(notch=FALSE, outlier.colour="red", outlier.shape=8,
               outlier.size=4, position = "dodge") +
  stat_summary(fun=mean, geom="point", shape=23, size=4)

ggsave(filename = "AB_notched_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)

p2CD <- ggplot(df_filt_CD, aes(x=Metadata_Well, y=NormTotalIntensity)) + 
  geom_boxplot(notch=FALSE, outlier.colour="red", outlier.shape=8,
               outlier.size=4, position = "dodge") +
  stat_summary(fun=mean, geom="point", shape=23, size=4)

ggsave(filename = "CD_notched_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)

p2EF <- ggplot(df_filt_EF, aes(x=Metadata_Well, y=NormTotalIntensity)) + 
  geom_boxplot(notch=FALSE, outlier.colour="red", outlier.shape=8,
               outlier.size=4, position = "dodge") +
  stat_summary(fun=mean, geom="point", shape=23, size=4)

ggsave(filename = "EF_notched_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)

p2 <- ggplot(df_filt_GH, aes(x=Metadata_Well, y=NormTotalIntensity)) + 
  geom_boxplot(notch=FALSE, outlier.colour="red", outlier.shape=8,
               outlier.size=4, position = "dodge") +
  stat_summary(fun=mean, geom="point", shape=23, size=4)

ggsave(filename = "GH_notched_bar.pdf", width = 8, height = 4, units = "in", path = output_dir)

# save summarized data (means)
outputNameMeans <- "merged_means.csv"
write_csv(by_well,file.path(output_dir, outputNameMeans))

# save normalized data with important columns
outputNameNorm <- "merged_norm.csv"
write_csv(df_selected,file.path(output_dir, outputNameNorm))



